mongo:
  host: "localhost"
  port: 27017
  user: "admin"
  pass: "admin"
  name: "gm_meet"
logging:
  version: 1 # <-- This is required
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"